### ISSUE TITLE
jupyter won't start if code.py present in /notebooks

### ISSUE THREAD

**Issue by Fatsie** [ipython/docker-notebook#46]
When code.py is present in /notebooks the server fails to start and this is the log:
>Traceback (most recent call last):
>  File "<string>", line 1, in <module>
>  File "/usr/local/lib/python3.4/dist-packages/IPython/__init__.py", line 48, in <module>
>    from .core.application import Application
>  File "/usr/local/lib/python3.4/dist-packages/IPython/core/application.py", line 24, in <module>
>    from IPython.core import release, crashhandler
>  File "/usr/local/lib/python3.4/dist-packages/IPython/core/crashhandler.py", line 28, in <module>
>    from IPython.core import ultratb
>  File "/usr/local/lib/python3.4/dist-packages/IPython/core/ultratb.py", line 110, in <module>
>    from IPython.core import debugger
>  File "/usr/local/lib/python3.4/dist-packages/IPython/core/debugger.py", line 59, in <module>
>    from pdb import Pdb as OldPdb
>  File "/usr/lib/python3.4/pdb.py", line 75, in <module>
>    import code
>  File "/notebooks/code.py", line 26
>    print "Warning: Batterij gebruiken om laag te kopen en hoog te verkopen is niet geimplementeerd"

Is seems that the line computing a hash with python3 tries to import code out of /usr/lib/python3.4/pdb.py and wrongly includes my version.

**Comment by Carreau** [comment]
[code](https://docs.python.org/2/library/code.html?highlight=code#module-code) is a stdlib module, the python work you cannot create file that have the same name as stdlib module or they are picked up first. Same will happend with `path.py` and many others.
