### ISSUE TITLE
Manual restart required everytime network connectivity changes (boot2docker)

### ISSUE THREAD

**Issue by jakirkham** [ipython/docker-notebook#47]
This occurs when having an existing container running when switching WiFi networks, switching to/from Ethernet, being disconnected. When this happens, the notebook cannot find the old kernel and complains it must restart. Ideally, restarting should not be required in this case. I notice this while using `boot2docker`.

**Comment by rgbkrk** [comment]
This is a problem overall with virtualbox, I face the same pain across other containers (non-ipython) as well. Same for when using kitematic, also affected by hopping on VPN tunnels, etc.

**Comment by jakirkham** [comment]
However, I don't experience this problem with `vagrant`. I am aware they use to have this problem, but I have not seen it in sometime and haven't upgraded VirtualBox. This leaves me to wonder whether there is simply something faulty with how `boot2docker` is operating.

Regardless, I believe you are right that the containers here are not the cause of the problem, but maybe a workaround would be nice.

Either way, I have opened an issue with `boot2docker` ( https://github.com/boot2docker/boot2docker/issues/945 ) and will close this one.

**Comment by jakirkham** [comment]
FWIW, some network connectivity issues were addressed through this PR ( https://github.com/boot2docker/boot2docker/pull/960 ), which should show up in the 1.7.1 release due this week. However, I don't find this full addresses this problem.
